import Head from "next/head";
import { BsDownload, BsEmojiSmile } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from "react-icons/ai";
import { IoDocumentAttachOutline } from "react-icons/io";
import { DiJava } from "react-icons/di";
import { FaServer, FaBook } from "react-icons/fa";
import { CgScreen, CgMoon } from "react-icons/cg";
import Image from "next/image";
import ProfilePic from "../public/profile-pic.png";
import { useState, useEffect} from "react";

export default function Home() {
  const name_text = "<thiago farias/>";
  const fileUrl = "Curriculo_EN_THIAGO.pdf";
  const fileName = "resume.pdf";
  const [text1, setText1] = useState("");

  const [theme, setTheme] = useState('');

  useEffect(() => {
    let localTheme = window.localStorage.getItem('theme');
    setTheme(localTheme);
  }, []);

  const switchTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    window.localStorage.setItem('theme', newTheme);
    setTheme(newTheme);
  };

  useEffect(() => {
    const timeout = setTimeout(() => {
      setText1(name_text.slice(0, text1.length + 1));
    }, 100);
    return () => clearTimeout(timeout);
  }, [text1]);


  return (
    <div>
      <Head>
        <title>Thiago Farias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={theme == 'light' ? "bg-gray-800 px-10" : "bg-white px-10"}>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-evenly">
            <h1
              className={
                theme == 'light'
                  ? "text-white text-xl font-burtons text-justify"
                  : "text-xl font-burtons text-justify"
              }
            >
              developedbythi
            </h1>

            <ul className="flex items-center">
              <li>
                <button onClick={switchTheme}>
                  <CgMoon
                    className={
                      theme == 'light'
                        ? "text-white cursor-pointer text-2xl"
                        : "cursor-pointer text-2xl"
                    }
                  />
                </button>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8"
                  href={fileUrl}
                  download={fileName}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-1 h-30">
            <h2 className="h-auto font-extrabold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500 pb-2">
              {text1}
            </h2>
            <p
              className={
                theme == 'light'
                  ? "text-md py-5 leading-8 text-white"
                  : "text-md py-5 leading-8 text-gray-800"
              }
            >
              hey there! i am thiago, currently living in brazil and working at
              a company called{" "}
              <a
                href="https://www.moskitcrm.com/"
                className="font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500"
              >
                Moskit CRM
              </a>
              .
            </p>
          </div>

          <div
            className={
              theme == 'light'
                ? "text-5xl flex justify-center gap-16 text-white"
                : "text-5xl flex justify-center gap-16 text-gray-600"
            }
          >
            <a href="https://www.linkedin.com/in/thiago-farias-b09280163/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/thiagosfarias">
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/thiagofarias.dev/">
              <AiFillInstagram />
            </a>
          </div>

          <div className="relative mx-auto rounded-full w-60 h-60 mt-10 overflow-hidden">
            <Image src={ProfilePic} layout="fill" objectFit="cover" />
          </div>

          <div className="flex flex-wrap justify-center gap-5">
            <div className="w-96 mt-6 mb-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-center shadow-lg pt-5 pb-5 rounded-xl">
              <FaServer className="pt-2 w-28 h-28 text-white mx-auto" />
              <h3 className="text-lg font-medium pt-3 pb-2">backend.</h3>
              <p className="text-gray-800 ml-3 mr-3 text-justify text-md">
                created applications using Java and Spring Framework, C# with
                .NET, mapping the databases with ORM frameworks such as MyBatis,
                JPA and DOMA; also using docker to improve the productivity
              </p>
            </div>

            <div className="w-96 mt-6 mb-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-center shadow-lg pt-5 pb-5 rounded-xl">
              <FaBook className="pt-2 w-28 h-28 text-white mx-auto" />
              <h3 className="text-lg font-medium pt-3 pb-2">education.</h3>
              <p className="text-gray-800 ml-3 mr-3 text-justify text-md">
                studied Information Systems at IFMA - Federal Institute of
                Maranhao
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
