import Head from "next/head";
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from "react-icons/ai";
import { FaServer, FaBook, FaBriefcase } from "react-icons/fa";
import { CgMoon, CgSun } from "react-icons/cg";
import Image from "next/image";
import ProfilePic from "../public/profile-pic.png";
import { useState, useEffect} from "react";

export default function Home() {
  const name_text = "<thiago farias/>";
  const fileUrl = "RESUME.pdf";
  const fileName = "resume.pdf";
  const [text1, setText1] = useState("");

  const [theme, setTheme] = useState('');

  useEffect(() => {
    let localTheme = window.localStorage.getItem('theme');
    setTheme(localTheme);
  }, []);

  const switchTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    window.localStorage.setItem('theme', newTheme);
    setTheme(newTheme);
  };

  useEffect(() => {
    const timeout = setTimeout(() => {
      setText1(name_text.slice(0, text1.length + 1));
    }, 100);
    return () => clearTimeout(timeout);
  }, [text1]);


  return (
    <div>
      <Head>
        <title>Thiago Farias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={theme == 'light' ? "bg-gray-800 px-10" : "bg-white px-10"}>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-evenly">
            <h1
              className={
                theme == 'light'
                  ? "text-white text-xl font-burtons text-justify"
                  : "text-xl font-burtons text-justify"
              }
            >
              developedbythi
            </h1>

            <ul className="flex items-center">
              <li>
                <button onClick={switchTheme}>
                  {
                    theme == 'light' ?
                    <CgSun className={"text-white cursor-pointer text-2xl"}
                  /> : 
                    <CgMoon className={"text-black cursor-pointer text-2xl"}/>
                  }
                </button>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8"
                  href={fileUrl}
                  download={fileName}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-1 h-30">
            <h2 className="h-auto font-extrabold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500 pb-2">
              {text1}
            </h2>
            <p
              className={
                theme == 'light'
                  ? "text-md py-5 leading-8 text-white"
                  : "text-md py-5 leading-8 text-gray-800"
              }
            >
              hey there! i am thiago, based in brazil and working at
              a company called{" "}
              <a
                href="https://www.moskitcrm.com/"
                className="font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500"
              >
                Moskit
              </a>
              .
            </p>
          </div>

          <div
            className={
              theme == 'light'
                ? "text-5xl flex justify-center gap-16 text-white"
                : "text-5xl flex justify-center gap-16 text-gray-600"
            }
          >
            <a href="https://www.linkedin.com/in/thiago-farias-b09280163/" target="_blank" rel="noreferrer" >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/thiagosfarias" target="_blank" rel="noreferrer" >
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/thiagofarias.dev/" target="_blank" rel="noreferrer" >
              <AiFillInstagram />
            </a>
          </div>

          <div className="relative mx-auto rounded-full w-60 h-60 mt-10 mb-10 overflow-hidden">
            <Image  alt="image" src={ProfilePic} layout="fill" objectFit="cover" />
          </div>

          <div className="flex flex-wrap justify-center gap-5">
            <div className="w-96 mt-6 mb-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-center shadow-lg pt-5 pb-5 rounded-xl">
              <FaServer className="pt-2 w-28 h-28 text-white mx-auto" />
              <h3 className="text-lg font-medium pt-3 pb-2">background.</h3>
              <p className="text-gray-800 ml-3 mr-3 text-justify text-md">
              highly skilled and motivated Backend Developer with expertise in Java and Groovy programming languages, 
              along with extensive knowledge of the Spring Framework and Quarkus Framework. 
              Proficient in event-driven development with messaging systems like ActiveMQ for efficient communication. 
              Acquainted with various databases, such as: MySQL, SQL Server, PostgreSQL and MariaDB. 
              Experienced in building and maintaining robust Rest APIs, SOAP services with HTTP and RPC protocols. 
              Passionate about delivering scalable and performant backend solutions.
              </p>
            </div>

            <div className="w-96 mt-6 mb-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-center shadow-lg pt-5 pb-5 rounded-xl">
              <FaBook className="pt-2 w-28 h-28 text-white mx-auto" />
              <h3 className="text-lg font-medium pt-3 pb-2">education.</h3>
              <p className="text-gray-800 ml-3 mr-3 text-justify text-md">
                studied Information Systems at IFMA - Federal Institute of
                Maranhao, troughtout the course had to cover a wide range of topics, 
                including database management, network infrastructure, cybersecurity, software development, project management, and data analytics. 
                Building a solid foundation in areas such as data modeling, data warehousing, system integration, and information security. 
                By delving into real-world case studies and hands-on projects, i learnt to apply theoretical concepts to practical scenarios.
              </p>
            </div>

            <div className="w-96 mt-6 mb-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-center shadow-lg pt-5 pb-5 rounded-xl">
              <FaBriefcase className="pt-2 w-28 h-28 text-white mx-auto" />
              <h3 className="text-lg font-medium pt-3 pb-2">where i been.</h3>
              <p className="text-gray-800 ml-3 mr-3 text-justify text-md">
                <ul className="grid-flow-row">
                  <li className="mb-3"><strong>ocidental informatica</strong> - Intern FullStack Developer | Sep 2019 - Feb 2020</li>
                  <li className="mb-3"><strong>agrotols</strong> - Junior FullStack Developer | Jan 2021 - Jul 2021</li>
                  <li className="mb-3"><strong>pulse</strong> - Junior FullStack Developer | Aug 2021 - Aug 2022</li>
                  <li className="mb-3"><strong>moskit</strong> - Mid Backend Developer | Sep 2022 - moment</li>
                </ul>
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
